### ISSUE TITLE
Update documentaion for Cross-cluster replication

### ISSUE THREAD

**Issue by monu-aws** [awsdocs/amazon-opensearch-service-developer-guide#101]
Hi team,

Starting from 2.7, Cross cluster replication would support replication of knn indices.
This change will only be available on managed service OS version 2.7 which is not yet released.

Requesting guidance on the process to update the public facing documentation.

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/replication.html#replication-limitations

Cross-cluster replication doesn't work with [data streams](https://opensearch.org/docs/latest/opensearch/data-streams/) or the [k-NN plugin](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/knn.html).

**Changed to**
Cross-cluster replication doesn't work with [data streams](https://opensearch.org/docs/latest/opensearch/data-streams/) ~~or the [k-NN plugin](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/knn.html)~~.
Cross-cluster replication doesn't work with [k-NN plugin](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/knn.html) for OpenSearch version less than 2.7.

**Comment by chatnish** [comment]
Hi Monu, I just sent you an email describing how to get this updated.
