### ISSUE TITLE
Add support for OpenSearch 1.3.x

### ISSUE THREAD

**Issue by bhrutledge** [awsdocs/amazon-opensearch-service-developer-guide#60]
I'm very new to OpenSearch in general, so forgive me if this isn't right place for this. From [What is Amazon OpenSearch Service? - Amazon OpenSearch Service](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html#choosing-version), the supported versions are 1.0 and 1.1. However, the [latest version](https://opensearch.org/docs/latest/version-history/) is 1.3.0 (or maybe [1.3.1](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.3.1.md)?), and I note that 1.2.3 updated Log4j.

**Comment by lizsnyder** [comment]
Hi @bhrutledge, Amazon OpenSearch Service adds support for new OpenSearch versions with a slight lag time, as there is internal work that needs to be done to incorporate and support the new version and features. 1.2 support is coming soon, followed by 1.3 several months after that.

You could consider subscribing to the RSS feed for the release notes so you'll be notified when we do add support: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/release-notes.html
