### ISSUE TITLE
Current AwsRequestSigningApacheInterceptor removes request content

### ISSUE THREAD

**Issue by xanperi** [awsdocs/amazon-opensearch-service-developer-guide#67]
Hello,

I am trying to use the java [AwsRequestSigningApacheInterceptor](https://github.com/awsdocs/amazon-opensearch-service-developer-guide/blob/7a55e54d9f883c39b25f78548b543ac98b887a7e/sample_code/java/aws-request-signing-apache-interceptor/src/main/java/com/amazonaws/http/AwsRequestSigningApacheInterceptor.java) provided here in my current code (which was using the v1 version of the java before) and thanks to test file also provided, I realized that the current code is removing the content of the request.
After debugging, it seems that the stream has already been read when it tries to copy back the content.
I am using a Java 11 micronaut project, and the [2.17.258] version of the `software.amazon.awssdk.auth` package. Could it be that a different version is needed for it to work as expected?

Thanks in advance

**Comment by lizsnyder** [comment]
@dblock @arunx2 FYI, can you please have a look at this?

For reference: https://github.com/awsdocs/amazon-opensearch-service-developer-guide/pull/63

**Comment by dblock** [comment]
The version in the docs now should work. Is this not the case? Share your code?

There’s a community supported version in https://github.com/acm19/aws-request-signing-apache-interceptor, feel free to open an issue against that repo with a repo/unit test and we can fix it there. The AWS docs just copy paste that code.

**Comment by dblock** [comment]
We should close this, I believe it's fixed everywhere. @lizsnyder

**Comment by lizsnyder** [comment]
Ack, thanks @dblock
