### ISSUE TITLE
Alerting destinations replaced by Notifications in OpenSearch 2.0+

### ISSUE THREAD

**Issue by kamingleung** [awsdocs/amazon-opensearch-service-developer-guide#74]
With OpenSearch version 2.0 and later, alerting destinations have been replaced with Notifications, a unified notifications system in OpenSearch. The [alerting page](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/alerting.html) and any applicable pages should be updated to reflect these changes:
- Introduction to Notifications plugin
- Existing destinations are automatically migrated to Notifications plugin as Channels
- If some destinations failed to migrate, they will continue to work
- Users will manage Channels in Notifications going forward

For reference: https://opensearch.org/docs/latest/monitoring-plugins/alerting/monitors/#questions-about-destinations

**Comment by lizsnyder** [comment]
Thanks @kamingleung, I have added a section on notifications: https://docs.amazonaws.cn/en_us/opensearch-service/latest/developerguide/alerting.html#alerting-notifications
