### ISSUE TITLE
Add a sample for OpenSearch Serverless request signing

### ISSUE THREAD

**Issue by dblock** [awsdocs/amazon-opensearch-service-developer-guide#79]
Coming from https://github.com/opensearch-project/opensearch-java/issues/287

**Comment by lizsnyder** [comment]
Hi @dblock is this separate from what we already have? https://github.com/awsdocs/amazon-opensearch-service-developer-guide/tree/master/sample_code/AmazonOpenSearchJavaClient-main

**Comment by lizsnyder** [comment]
@dblock can we also close this? I believe we addressed it here: https://github.com/awsdocs/amazon-opensearch-service-developer-guide/pull/91
