### ISSUE TITLE
Sigv4 signing documentation is obsolete

### ISSUE THREAD

**Issue by dblock** [awsdocs/amazon-opensearch-service-developer-guide#80]
There are much simpler ways to do this now with newer clients, see https://opensearch.org/blog/aws-sigv4-support-for-clients/

**Comment by dblock** [comment]
cc: @wbeckler

**Comment by roigamliel** [comment]
@dblock - would this work with Serverless as well? The signature part that is (assuming I only use it for supported API's). The service name for Serverless is aoss, so wondering of using AwsSdk2Transport and OpenSearchClient would work.

Thanks!

**Comment by dblock** [comment]
@roigamliel Sigv4 support for Serverless is now done, see https://github.com/opensearch-project/opensearch-clients/issues/44 for the umbrella item. Various transport implementations now support it properly. I just updated https://github.com/dblock/opensearch-java-client-demo with working code.
