### ISSUE TITLE
SigV4 request signing docs seem to be incorrect

### ISSUE THREAD

**Issue by harshavamsi** [awsdocs/amazon-opensearch-service-developer-guide#89]
In this part of the docs, it states that just using the unsigned-payload attribute for the header value should allow signing to work but it does not seem to be the case. I've had to compute the payload manually here -- https://github.com/opensearch-project/opensearch-py/pull/268

The x-amz-content-sha256 header is required for all AWS Signature Version 4 requests. It provides a hash of the request payload. For OpenSearch Serverless, include it with one of the following + "/" + id values when you build the canonical request for signing:

- If there's a request payload, set the value to its Secure Hash Algorithm (SHA) cryptographic hash (SHA256).

- If there's no request payload, set the value to e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, which is the hash of an empty string.

- In either of the above two cases, you can also use the literal string UNSIGNED-PAYLOAD as the value of the x-amz-content-sha256 header.

**Comment by lizsnyder** [comment]
@harshavamsi can you please link to the docs you're referring to?

**Comment by harshavamsi** [comment]
@lizsnyder https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-clients.html

**Comment by harshavamsi** [comment]
``` // Serverless collections expect this header in all requests with an HTTP body. The payload doesn't need to be signed; any value is fine.
      request.headers['x-amz-content-sha256'] = 'UNSIGNED-PAYLOAD';
```

I see this in the JavaScript example, but my experimentation leads me to believe otherwise.

**Comment by dblock** [comment]
The JS sample that's in https://github.com/awsdocs/amazon-opensearch-service-developer-guide/blob/master/doc_source/serverless-clients.md#javascript worked fine for me with or without `x-amz-content-sha256`. Do you have a repro @harshavamsi?
