### ISSUE TITLE
AwsRequestSigningApacheInterceptorTest is failing

### ISSUE THREAD

**Issue by remcowesterhoud** [awsdocs/amazon-opensearch-service-developer-guide#96]
## Description

The [testPostSigner()](https://github.com/awsdocs/amazon-opensearch-service-developer-guide/blob/master/sample_code/java/aws-request-signing-apache-interceptor/src/test/java/com/amazonaws/http/AwsRequestSigningApacheInterceptorTest.java#L82-L112) method is failing reproducibly.

```
org.opentest4j.AssertionFailedError: 
Expected :{"test": "val"}
Actual   :
```

Presumably this happens because during the signing of the request the content of the request is read. This results in the position of the `InputStream` to be moved to the end of the byte array. Next when the request is wrapped to make it possibly to retry here:

```java
if (request instanceof HttpEntityEnclosingRequest) {
    HttpEntityEnclosingRequest httpEntityEnclosingRequest =
            (HttpEntityEnclosingRequest) request;
    if (httpEntityEnclosingRequest.getEntity() != null) {
        BasicHttpEntity basicHttpEntity = new BasicHttpEntity();
        basicHttpEntity.setContent(signedRequest.contentStreamProvider()
                .orElseThrow(() -> new IllegalStateException("There must be content"))
                .newStream());
        // wrap into repeatable entity to support retries
        httpEntityEnclosingRequest.setEntity(new BufferedHttpEntity(basicHttpEntity));
    }
}
```

The `basicHttpEntity` content is set to the previously-read `InputStream`. As a result creating the `BufferedHttpEntity` will result in an entity containing an empty buffer, as this will again try to read the `InputStream`. As the position is already at the end of the byte array it will read nothing.

Adding `basicHttpEntity.getContent().reset();` before creating the `BufferedHttpEntity` resolves the issue.

## Reproduce
Run the tests and it should fail.

**Comment by dblock** [comment]
Is this still a problem with https://github.com/acm19/aws-request-signing-apache-interceptor? That's a community-maintained version of this code. If the issue persists there, let's fix it?

**Comment by remcowesterhoud** [comment]
Sounds good, I wasn't aware of this project. Thanks for showing me 🙇‍♂️

**Comment by dblock** [comment]
> Sounds good, I wasn't aware of this project. Thanks for showing me 🙇‍♂️

Thanks for reporting the issue. We're working on cleaning up the docs in a way that that project is more discoverable.
